version: "3.9"  

services:
  chat-backend:
    build:
      context: .
      dockerfile: Dockerfile  
    container_name: chat_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app               
    depends_on:
      - ollama
    environment:
      DEBUG: "True"
      OLLAMA_URL: "http://ollama:11434"

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    tty: true

volumes:
  ollama_data:
