
Portfolio:
  Host: 127.0.0.1
  Port: 50

ChatBot:
  Host: 127.0.0.1
  Port: 40

AIModel:
  Model: dolphin-phi
  Host: 127.0.0.1
  Port: 11434

DBConfig:
  DBName: portfolio_z605
  User: vidushigandhi27
  Password: yFaHwt40JrAXok6mV4ZUgEaCZGIzIA1S
  Host: dpg-cvvrsva4d50c739mbpt0-a.oregon-postgres.render.com
  Port: 5432


